import type { AppProps } from 'next/app'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify'
import { ThemeProvider } from 'styled-components'
import GlobalStyles from '../assets/styles/global'
import 'react-toastify/dist/ReactToastify.css'
import theme from '../assets/styles/theme'
import Layout from '../components/Layout'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme={theme}>
        <Head>
            <title>olar. marketplace</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/" />
        </Head>
        <Layout>
            <Component {...pageProps} />
        </Layout>
        <GlobalStyles />
        <ToastContainer />
    </ThemeProvider>
  )
}
